/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Pin_1.h>
#include <Pin_1_aliases.h>
#include <Clock_1.h>
#include <Status_Reg_1.h>
#include <CapSense_1.h>
#include <CapSense_1_CSHL.h>
#include <CapSense_1_TunerHelper.h>
#include <CapSense_1_SMS.h>
#include <CapSense_1_PVT.h>
#include <CapSense_1_IP.h>
#include <PWM_1.h>
#include <Clock_3.h>
#include <LED_G.h>
#include <LED_G_aliases.h>
#include <Pin_SW.h>
#include <Pin_SW_aliases.h>
#include <LED_R.h>
#include <LED_R_aliases.h>
#include <PWM_2.h>
#include <Clock_4.h>
#include <LED_B.h>
#include <LED_B_aliases.h>
#include <CapSense_1_SampleClk.h>
#include <CapSense_1_Sns_aliases.h>
#include <CapSense_1_SenseClk.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

